### ISSUE TITLE
Error on starting

### ISSUE THREAD

**Issue by abrolag** [dtomas/MediaTray#1]
I get the message:
Typeerror: 'NoneType' object is not iterable
After closing that window MediaTray appears to work quite correctly. This happens with V 0.1.3 and 0.1.4

This is on a variety of 32 and 64bit machines with debian jessie.

**Comment by dtomas** [comment]
Could you provide a traceback (click on Details, then Bug Report)?

**Comment by abrolag** [comment]
On Mon, 18 Apr 2016 22:38:00 -0700
dtomas notifications@github.com wrote:

> Could you provide a traceback (click on Details, then Bug Report)?
> 
> ---
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/dtomas/MediaTray/issues/1#issuecomment-211736682

Traceback attached.

Thanks for getting back so quickly.

## 

Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by dtomas** [comment]
I did not receive your attachment, I think github might have stripped it.

**Comment by abrolag** [comment]
On Tue, 19 Apr 2016 00:01:03 -0700
dtomas notifications@github.com wrote:

> I did not receive your attachment, I think github might have stripped it.
> 
> ---
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/dtomas/MediaTray/issues/1#issuecomment-211762412

Hmm, there's me trying to be helpful :(

OK. it's in this email below. Unfortunately claws mail will word wrap it.

---

Traceback (most recent call last):
  File "/home/will/LocalProgs/MediaTray/AppletRun", line 18, in <module>
    MediaTrayMain().mainloop(sys.argv)
  File "/home/will/LocalProgs/MediaTray/mediatray/main.py", line 74, in mainloop
    volume_monitor=gio.volume_monitor_get(),
  File "/home/will/LocalProgs/MediaTray/TrayLib/traylib/main.py", line 76, in
mainloop rox.mainloop()
  File
"/home/will/LocalProgs/MediaTray/rox-lib/ROX-Lib2/python/rox/**init**.py", line
359, in mainloop g.main() File
"/home/will/LocalProgs/MediaTray/rox-lib/ROX-Lib2/python/rox/tasks.py", line
266, in _handle_run_queue task._resume() File
"/home/will/LocalProgs/MediaTray/rox-lib/ROX-Lib2/python/rox/tasks.py", line
212, in _resume new_blockers = self.next() File
"/home/will/LocalProgs/MediaTray/TrayLib/traylib/managed_tray.py", line 20, in
_manage for x in manage(): TypeError: 'NoneType' object is not iterable

---

## 

Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by dtomas** [comment]
It was a bug in TrayLib. To update, you must "git pull" as well as "git submodule update".

**Comment by abrolag** [comment]
On Tue, 19 Apr 2016 00:28:54 -0700
dtomas notifications@github.com wrote:

> It was a bug in TrayLib. To update, you must "git pull" as well as "git submodule update".
> 
> ---
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/dtomas/MediaTray/issues/1#issuecomment-211771236

Thanks. All fine now. I have several machines at home and at work, so I'll
populate to upgrade round them :)

## 

Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by abrolag** [comment]
On Tue, 19 Apr 2016 00:28:54 -0700
dtomas notifications@github.com wrote:

> It was a bug in TrayLib. To update, you must "git pull" as well as "git submodule update".
> 
> ---
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/dtomas/MediaTray/issues/1#issuecomment-211771236

Spoke too soo :(

It loads on the Icon bar fine, but when plugging in a USB stck I get the
following:

---

Traceback (most recent call last):
  File "/home/will/LocalProgs/MediaTray/AppletRun", line 18, in <module>
    MediaTrayMain().mainloop(sys.argv)
  File "/home/will/LocalProgs/MediaTray/mediatray/main.py", line 74, in mainloop
    volume_monitor=gio.volume_monitor_get(),
  File "/home/will/LocalProgs/MediaTray/TrayLib/traylib/main.py", line 88, in
mainloop rox.mainloop()
  File
"/home/will/LocalProgs/MediaTray/rox-lib/ROX-Lib2/python/rox/**init**.py", line
359, in mainloop g.main() File
"/home/will/LocalProgs/MediaTray/mediatray/mediaicon_manager.py", line 27, in
volume_added screen, volume_monitor), File
"/home/will/LocalProgs/MediaTray/mediatray/mediaicon.py", line 78, in **init**
self, icon_config, win_config, screen, volume_monitor File
"/home/will/LocalProgs/MediaTray/mediatray/mounticon.py", line 41, in **init**
WinIcon.**init**(self, icon_config, win_config, screen) File
"/home/will/LocalProgs/MediaTray/TrayLib/traylib/winicon.py", line 42, in
**init** screen.connect( AttributeError: 'NoneType' object has no attribute
'connect'

---

If I close that window and click on the MediaTray Icon, I get:

---

Traceback (most recent call last):
  File "/home/will/LocalProgs/MediaTray/AppletRun", line 18, in <module>
    MediaTrayMain().mainloop(sys.argv)
  File "/home/will/LocalProgs/MediaTray/mediatray/main.py", line 74, in mainloop
    volume_monitor=gio.volume_monitor_get(),
  File "/home/will/LocalProgs/MediaTray/TrayLib/traylib/main.py", line 88, in
mainloop rox.mainloop()
  File
"/home/will/LocalProgs/MediaTray/rox-lib/ROX-Lib2/python/rox/**init**.py", line
359, in mainloop g.main() File
"/home/will/LocalProgs/MediaTray/TrayLib/traylib/icon.py", line 570, in
**button_release_event self.click(event.time) File
"/home/will/LocalProgs/MediaTray/mediatray/main_icon.py", line 43, in click not
self.__mediaicon_config.hide_unmounted File
"/home/will/LocalProgs/MediaTray/TrayLib/traylib/config.py", line 25, in
__set** obj.emit(self._signal_name) File
"/home/will/LocalProgs/MediaTray/mediatray/mediaicon.py", line 73, in <lambda>
lambda config: self.update_visibility() File
"/home/will/LocalProgs/MediaTray/TrayLib/traylib/icon.py", line 199, in
update_visibility if not self.__config.hidden and self.make_visibility(): File
"/home/will/LocalProgs/MediaTray/mediatray/mediaicon.py", line 256, in
make_visibility return self.is_mounted or not
self.__mediaicon_config.hide_unmounted File
"/home/will/LocalProgs/MediaTray/mediatray/mounticon.py", line 98, in
is_mounted return self.__is_mounted AttributeError: 'MediaIcon' object has no
attribute '_MountIcon__is_mounted'

---

## 

Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by dtomas** [comment]
Another TrayLib bug (related to python-wnck not being present), please update.

**Comment by abrolag** [comment]
On Tue, 19 Apr 2016 05:15:14 -0700
dtomas notifications@github.com wrote:

> Another TrayLib bug (related to python-wnck not being present), please update.
> 
> Thanks for keeping up with this. I can now confirm there are no more error
> messages. I double-checked by rebooting and everything seems fine with both a
> USB stick, and a USB SSD.

## 

Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.
